name: Docker Image CI

on:
  push:
    tags:
      - 'v*'  # This will trigger on any tag that starts with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: quay.io/${{ vars.QUAY_REPOSITORY }}:${{ github.ref_name }}
